DELIMITER $$
CREATE TRIGGER trigger_usuario_delete
  BEFORE DELETE ON SpotifyClone.USERS
  FOR EACH ROW
BEGIN
  DELETE FROM SpotifyClone.FOLLOWERS
  WHERE USER_ID = OLD.USER_ID;
  DELETE FROM SpotifyClone.`HISTORY`
  WHERE USER_ID = OLD.USER_ID;
END $$

DELIMITER ;
