DELIMITER $$
CREATE TRIGGER trigger_usuario_delete
  AFTER DELETE ON SpotifyClone.USERS
  FOR EACH ROW
BEGIN
  DELETE FROM SpotifyClone.FOLLOWERS F
  WHERE F.USER_ID = OLD.USER_ID;
  DELETE FROM SpotifyClone.`HISTORY` H
  WHERE H.USER_ID = OLD.USER_ID;
END $$

DELIMITER ;
