DELIMITER $$
CREATE FUNCTION quantidade_musicas_no_historico(USER_ID INT UNSIGNED)
RETURNS INT UNSIGNED READS SQL DATA
BEGIN
  DECLARE AMOUNT_SONGS INT UNSIGNED;
  SELECT
      COUNT(H.SONG_ID)
    FROM
      SpotifyClone.`HISTORY` H
    WHERE
      H.USER_ID = USER_ID
    INTO AMOUNT_SONGS;
  RETURN AMOUNT_SONGS;
END $$

DELIMITER ;
